export type ConfigDto = {
  language: string;
  username: string;
  chatId: number;
  subscribe: string[];
  unsubscribe: string[];
  onlyBotrix: boolean;
  usernamePattern: RegExp;
  botrixId: number;
  textInfo: string;
  viewersLive: number;
  moderatorCommands: boolean;
  removePlayerCommand: string;
  clearListCommand: string;
  liveCommand: string;
  nextLiveCommand: string;
  stateListOnStartup: boolean;
  openListCommand: string;
  closeListCommand: string;
};
